/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
 ARAGON: [
    'ARAGON/examen-aragon',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ARAGON/asignatura',
        },
      ],
    },
  ],
  ASTURIAS: [
    'ASTURIAS/examen-asturias',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ASTURIAS/asignatura',
        },
      ],
    },
  ],
  ANDALUCIA: [
    'ANDALUCÍA/examen-andalucia',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ANDALUCÍA/asignatura',
        },
      ],
    },
  ],
  CANTABRIA: [
    'CANTABRIA/examen-cantabria',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'CANTABRIA/asignatura',
        },
      ],
    },
  ],
  CASTILLAlamancha: [
    'CASTILLA LA MANCHA/examen-castilla-la-mancha',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'CASTILLA LA MANCHA/asignatura',
        },
      ],
    },
  ],
  CASTILLAleon: [
    'CASTILLA Y LEÓN/examen-castilla-y-leon',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'CASTILLA Y LEÓN/asignatura',
        },
      ],
    },
  ],
  CATALUÑA: [
    'CATALUÑA/examen-CATALUÑA',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'CATALUÑA/asignatura',
        },
      ],
    },
  ],
  COMUNIDADVALENCIANA: [
    'COMUNIDAD VALENCIANA/examen-valencia',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'COMUNIDAD VALENCIANA/asignatura',
        },
      ],
    },
  ],
  EXTREMADURA: [
    'EXTREMADURA/examen-extremadura',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'EXTREMADURA/asignatura',
        },
      ],
    },
  ],
  GALICIA: [
    'GALICIA/examen-galicia',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'GALICIA/asignatura',
        },
      ],//在其他的也添加这个
    },
  ],
  islabaleares: [
    'ISLAS BALEARES/examen-islas-baleares',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ISLAS BALEARES/asignatura',
        },
      ],
    },
  ],
  islascanarias: [
    'ISLAS CANARIAS/examen-islas-canarias',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ISLAS CANARIAS/asignatura',
        },
      ],
    },
  ],
  RIOJA: [
    'LA RIOJA/examen-la-rioja',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'LA RIOJA/asignatura',
        },
      ],
    },
  ],
  MADRID: [
    'MADRID/examen-madrid',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'MADRID/asignatura',
        },
      ],
    },
  ],
  murcia: [
    'MURCIA/examen-murcia',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'MURCIA/asignatura',
        },
      ],
    },
  ],
  navarra: [
    'NAVARRA/examen-navarra',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'NAVARRA/asignatura',
        },
      ],
    },
  ],
  paisvasco: [
    'PAÍS VASCO/examen-pais-vasco',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'PAÍS VASCO/asignatura',
        },
      ],
    },
  ],
  fecha: [
    'fecha/fecha-de-ebau',
    
  ],
  contactar: [
    'contactar/contactar',
  ]
}

module.exports = sidebars
