/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  //还差添加一个aragon
  ASTURIAS: [
    'ASTURIAS/examen-asturias',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ASTURIAS/asignatura',
        },
      ],
    },
  ],
  ANDALUCIA: [
    'ANDALUCÍA/examen-andalucia',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ANDALUCÍA/asignatura',
        },
      ],
    },
  ],
  CANTABRIA: [
    'CANTABRIA/examen-cantabria',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'CANTABRIA/asignatura',
        },
      ],
    },
  ],
  CASTILLAlamancha: [
    'CASTILLA LA MANCHA/examen-castilla-la-mancha',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'CASTILLA LA MANCHA/asignatura',
        },
      ],
    },
  ],
  CASTILLAleon: [
    'CASTILLA Y LEÓN/examen-castilla-y-leon',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'CASTILLA Y LEÓN/asignatura',
        },
      ],
    },
  ],
  CATALUÑA: [
    'CATALUÑA/examen-CATALUÑA',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'CATALUÑA/asignatura',
        },
      ],
    },
  ],
  COMUNIDADVALENCIANA: [
    'COMUNIDAD VALENCIANA/examen-valencia',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'COMUNIDAD VALENCIANA/asignatura',
        },
      ],
    },
  ],
  EXTREMADURA: [
    'EXTREMADURA/examen-extremadura',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'EXTREMADURA/asignatura',
        },
      ],
    },
  ],
  GALICIA: [
    'GALICIA/examen-galicia',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'GALICIA/asignatura',
        },
      ],//在其他的也添加这个
    },
  ],
  islabaleares: [
    'ISLAS BALEARES/examen-islas-baleares',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ISLAS BALEARES/asignatura',
        },
      ],
    },
  ],
  islascanarias: [
    'ISLAS CANARIAS/examen-islas-canarias',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ISLAS CANARIAS/asignatura',
        },
      ],
    },
  ],
  RIOJA: [
    'LA RIOJA/examen-la-rioja',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'LA RIOJA/asignatura',
        },
      ],
    },
  ],
  MADRID: [
    'MADRID/examen-madrid',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'MADRID/asignatura',
        },
      ],
    },
  ],
  murcia: [
    'MURCIA/examen-murcia',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'MURCIA/asignatura',
        },
      ],
    },
  ],
  navarra: [
    'NAVARRA/examen-navarra',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'NAVARRA/asignatura',
        },
      ],
    },
  ],
  paisvasco: [
    'PAÍS VASCO/examen-pais-vasco',
    {
      label: 'ASIGNATURAS',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'PAÍS VASCO/asignatura',
        },
      ],
    },
  ],
  fecha: [
    'fecha/fecha-de-ebau',
    
  ],
  contactar: [
    'contactar/contactar',
  ],
  skill: [
    'skill/introduction',
    {
      label: 'Vue',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        'skill/vue/vue-reactive-data-object',
        'skill/vue/vue-reactive-data-array',
        'skill/vue/vue-reactive-data-basic-type',
        'skill/vue/vue-component',
        'skill/vue/pinia',
      ],
    },
    {
      label: 'React',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/react',
        },
      ],
    },
    {
      label: 'Web',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/web',
        },
      ],
    },
    {
      label: 'JavaScript',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/js',
        },
      ],
    },
    {
      label: 'Node',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/node',
        },
      ],
    },
    {
      label: 'Css',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: ['skill/css/tailwind-css-usage', 'skill/css/func-and-useful-css-tips'],
    },
    {
      label: 'Go',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        'skill/go/go-environment-install',
        'skill/go/go-json-usage',
        'skill/go/go-send-http-request',
        'skill/go/go-call-js',
        'skill/go/go-concurrent',
        'skill/go/try-gin-framework'
      ],
    },
    {
      label: '算法',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/algorithm',
        },
      ],
    },
    {
      label: '逆向',
      type: 'category',
      link: {
        title: '逆向笔记',
        description: 'Web逆向与安卓逆向笔记',
        type: 'generated-index',
        keywords: ['reverse', 'web', 'android', 'frida'],
      },
      items: [
        {
          label: '安卓',
          type: 'category',
          link: {
            type: 'generated-index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/reverse/android',
            },
          ],
        },
        {
          label: 'Web',
          type: 'category',
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/reverse/web',
            },
          ],
        },
        {
          label: '密码学',
          type: 'category',
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/reverse/crypto',
            },
          ],
        },
      ],
    },
    {
      label: 'Docker',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/docker',
        },
      ],
    },
    {
      label: '数据库',
      type: 'category',
      link: {
        // title: '',
        // description: '',
        type: 'generated-index',
        keywords: ['database', 'mysql', 'mongodb', 'redis', 'elasticsearch'],
      },
      items: [
        {
          label: 'Mysql',
          type: 'category',
          link: {
            type: 'doc',
            id: 'skill/database/mysql/mysql-note',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/database/mysql',
            },
          ],
        },
        {
          label: 'MongoDB',
          type: 'category',
          link: {
            type: 'doc',
            id: 'skill/database/mongo/mongodb-note',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/database/mongo',
            },
          ],
        },
        {
          label: 'Redis',
          type: 'category',
          link: {
            type: 'doc',
            id: 'skill/database/redis/redis-note',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/database/redis',
            },
          ],
        },
        {
          label: 'Elasticsearch',
          type: 'category',
          link: {
            type: 'doc',
            id: 'skill/database/elasticsearch/elasticsearch-note',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/database/elasticsearch',
            },
          ],
        },
      ],
    },
    {
      label: '杂项',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/other',
        },
      ],
    },
  ],
  tools: [
    'tools/introduction',
    'tools/everything-quick-search-local-files',
    'tools/wappalyzer-recognize-technology',
    'tools/windows-custom-right-click-menu',
    'tools/vscode-config',
    'tools/idea-config',
    'tools/vite-plugin',
    'tools/wappalyzer-recognize-technology',
    'tools/jetbrains-product-activation-method',
  ]
}

module.exports = sidebars
